services:
  - type: web
    name: hydrological-analysis-tool
    env: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: gunicorn main:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: true
